import { Routes } from "@/@types/routes";

export const data: Routes[] = [
  {
    id: "EXPRESSO",
    name: "Rota Expresso",
    tripLength: 15,
    departures: [
      "6h30",
      "7h30",
      "8h40",
      "9h50",
      "11h00",
      "12h10",
      "13h20",
      "14h30",
      "15h40",
      "16h50",
      "18h00",
      "19h10",
      "20h10",
      "21h10",
      "22h30",
    ],
    departureLocation: "Ondina/PAF1",
    arrivalLocation: "Circular",
    servedLocations: [
      "Ondina/PAF1",
      "Centro de Esportes",
      "Residência Universitária Garibaldi",
      "Canela",
      "Economia",
      "Belas Artes",
      "Reitoria",
      "Creche",
      "Politécnica",
      "Arquitetura",
      "Geociências",
    ],
    stops: {
      departure: [
        "Ondina/PAF1",
        "Portaria Principal",
        "Centro de Esportes",
        "Residência Universitária Garibaldi",
        "Canela/ICS/FAMEB",
        "Economia",
        "Belas Artes",
      ],
      arrival: [
        "Reitoria",
        "Creche",
        "Politécnica",
        "Arquitetura",
        "Geociências",
        "Ondina/PAF1",
      ],
    },
    obs: "20h10 é o último horário a entrar em São Lázaro",
  },
  {
    id: "B1",
    name: "Rota B1",
    tripLength: 11,
    departures: [
      "6h10",
      "7h00",
      "8h00",
      "9h00",
      "10h00",
      "11h00",
      "12h00",
      "13h00",
      "15h00",
      "16h00",
      "17h00",
      "18h00",
      "19h00",
      "20h30",
      "21h40",
      "22h20",
    ],
    departureLocation: "Ondina/PAF1",
    arrivalLocation: "Reitoria",
    servedLocations: [
      "Ondina/PAF1",
      "Residência Universitária Garibaldi",
      "Canela",
      "Reitoria",
      "Creche",
      "Politécnica",
      "Arquitetura",
      "Geociências",
    ],
    stops: {
      departure: [
        "Ondina/PAF1",
        "Residência Universitária Garibaldi",
        "Canela/ICS/FAMEB",
        "Reitoria",
      ],
      arrival: [
        "Reitoria",
        "Creche",
        "Politécnica",
        "Arquitetura",
        "Geociências",
        "Ondina/PAF1",
      ],
    },
    obs: "20h30 é o último horário a entrar em São Lázaro",
  },
  {
    id: "B2",
    name: "Rota B2",
    tripLength: 13,
    departures: [
      "6h00",
      "7h00",
      "8h00",
      "9h00",
      "10h00",
      "11h00",
      "12h00",
      "14h30",
      "16h00",
      "17h40",
      "18h30",
      "18h50",
      "20h30",
      "21h40",
      "22h30",
    ],
    departureLocation: "Ondina/PAF1",
    arrivalLocation: "Reitoria",
    servedLocations: [
      "Ondina/PAF1",
      "Residência Universitária Garibaldi",
      "Residência I, Vitória",
      "Deli&Cia",
      "Reitoria",
      "Creche",
      "Politécnica",
      "Arquitetura",
      "Geociências",
    ],
    stops: {
      departure: [
        "Ondina/PAF1",
        "Residência Universitária Garibaldi",
        "Arquitetura",
        "Politécnica",
        "Creche",
        "Reitoria",
      ],
      arrival: [
        "Reitoria",
        "Residência I, Vitória",
        "Deli&Cia",
        "São Lázaro",
        "Politécnica",
        "Arquitetura",
        "Geociências",
        "Ondina/PAF1",
      ],
    },
    obs: "20h30 é o último horário a entrar em São Lázaro",
  },
  {
    id: "B3",
    name: "Rota B3",
    tripLength: 15.5,
    departures: [
      "6h30",
      "7h30",
      "8h40",
      "9h50",
      "11h20",
      "12h30",
      "14h00",
      "15h30",
      "16h30",
      "18h00",
      "19h10",
      "20h30",
      "21h40",
      "22h20",
    ],
    departureLocation: "Direito",
    arrivalLocation: "Ondina/PAF1",
    servedLocations: [
      "Direito",
      "Música",
      "ISC",
      "Odontologia",
      "Nutrição",
      "Ondina/PAF1",
      "Residência Universitária Garibaldi",
      "Deli&Cia",
      "Reitoria",
      "Creche",
      "Politécnica",
      "Arquitetura",
      "Geociências",
    ],
    stops: {
      departure: [
        "Direito",
        "Deli&Cia",
        "Escola de Música",
        "Reitoria",
        "Creche",
        "Politécnica",
        "Arquitetura",
        "Geociências",
        "Ondina/PAF1",
      ],
      arrival: [
        "Ondina/PAF1",
        "Residência Universitária Garibaldi",
        "Arquitetura",
        "São Lázaro",
        "Politécnica",
        "Creche",
        "Reitoria",
        "Escola de Música",
        "Direito",
      ],
    },
    obs: "20h30 é o último horário a entrar em São Lázaro",
  },
  {
    id: "B4",
    name: "Rota B4",
    tripLength: 14,
    departures: [
      "6h20",
      "7h20",
      "8h20",
      "9h30",
      "10h40",
      "11h40",
      "12h40",
      "14h00",
      "15h20",
      "16h30",
      "17h40",
      "20h00",
      "21h20",
      "22h30",
    ],
    departureLocation: "Ondina/PAF1",
    arrivalLocation: "Economia",
    servedLocations: [
      "Ondina/PAF1",
      "Residência Universitária Garibaldi",
      "Reitoria",
      "Economia",
      "Belas Artes",
      "São Lázaro",
      "Creche",
      "Politécnica",
      "Arquitetura",
      "Geociências",
    ],
    stops: {
      departure: [
        "Ondina/PAF1",
        "Residência Universitária Garibaldi",
        "Arquitetura",
        "Politécnica",
        "Creche",
        "Reitoria",
        "Economia",
      ],
      arrival: [
        "Economia",
        "Belas Artes",
        "Reitoria",
        "Creche",
        "Politécnica",
        "São Lázaro",
        "Arquitetura",
        "Geociências",
        "Ondina/PAF1",
      ],
    },
    obs: "20h00 é o último horário a entrar em São Lázaro",
  },
  {
    id: "B5",
    name: "Rota B5",
    tripLength: 17,
    departures: [
      "6h20",
      "7h30",
      "9h30",
      "10h40",
      "11h40",
      "12h40",
      "13h20",
      "15h00",
      "16h30",
      "17h40",
      "19h00",
      "20h00",
      "21h00",
      "22h00",
    ],
    departureLocation: "Facom",
    arrivalLocation: "Reitoria",
    servedLocations: [
      "Facom",
      "Residência Universitária Garibaldi",
      "Arquitetura",
      "São Lázaro",
      "Politécnica",
      "Creche",
      "Reitoria",
      "Geociências",
      "Residência I, Vitória",
      "Deli&Cia",
      "Ondina/PAF1",
    ],
    stops: {
      departure: [
        "Facom",
        "Residência Universitária Garibaldi",
        "Arquitetura",
        "São Lázaro",
        "Politécnica",
        "Creche",
        "Reitoria",
      ],
      arrival: [
        "Reitoria",
        "Residência I, Vitória",
        "Deli&Cia",
        "Politécnica",
        "São Lázaro",
        "Arquitetura",
        "Geociências",
        "Ondina/PAF1",
      ],
    },
    obs: "20h00 é o último horário a entrar em São Lázaro",
  },
];
