import { Routes } from "@/@types/routes";

export const routesData: Routes[] = [
  {
    id: "EXPRESSO",
    name: "Rota Expresso",
    tripLength: 13,
    departures: [
      "6h30",
      "7h30",
      "8h40",
      "9h50",
      "11h00",
      "12h20",
      "13h20",
      "14h30",
      "15h40",
      "16h50",
      "18h00",
      "19h10",
      "20h10",
      "21h10",
      "22h30",
    ],
    departureLocation: "Estacionamento PAF.1 Matemática",
    arrivalLocation: "Circular",
    servedLocations: [
      "Estacionamento PAF.1 Matemática",
      "Av. Garibaldi",
      "Campus Vale do Canela",
      "Viaduto Campo Grande",
      "Avenida 7 de Setembro - Faculdade de Economia",
      "Belas Artes",
      "Reitoria",
      "Creche — Canela",
      "Politécnica",
      "Arquitetura",
      "Estacionamento Geociências",
    ],
    stops: {
      departure: [
        "Estacionamento PAF.1 Matemática",
        "Av. Garibaldi",
        "Campus Vale do Canela",
        "Viaduto Campo Grande",
        "Avenida 7 de Setembro - Faculdade de Economia",
        "Belas Artes",
      ],
      arrival: [
        "Reitoria",
        "Creche — Canela",
        "Politécnica",
        "Arquitetura",
        "Estacionamento Geociências",
        "Estacionamento PAF.1 Matemática",
      ],
    },
    obs: "20h10 é o último horário a entrar na Piedade",
  },
  {
    id: "B1",
    name: "Rota B1",
    tripLength: 11,
    departures: [
      "6h10",
      "7h00",
      "8h00",
      "9h00",
      "10h00",
      "11h00",
      "12h00",
      "13h00",
      "15h00",
      "16h00",
      "17h00",
      "18h00",
      "19h00",
      "20h30",
      "21h40",
      "22h20",
    ],
    departureLocation: "Estacionamento São Lázaro",
    arrivalLocation: "Reitoria",
    servedLocations: [
      "Estacionamento São Lázaro",
      "Politécnica",
      "Arquitetura",
      "Viaduto Federação",
      "Residência 5",
      "Estacionamento Geociências",
      "Estacionamento PAF I Matemática",
      "Av. Garibaldi",
      "Campus Vale do Canela Entrada ICS",
      "Viaduto Campo Grande",
      "Belas Artes",
      "Reitoria",
      "Creche – Canela",
    ],
    stops: {
      departure: [
        "Estacionamento São Lázaro",
        "Politécnica",
        "Arquitetura",
        "Viaduto Federação",
        "Residência 5",
        "Estacionamento Geociências",
        "Estacionamento PAF I Matemática",
      ],
      arrival: [
        "Av. Garibaldi",
        "Campus Vale do Canela Entrada ICS",
        "Viaduto Campo Grande",
        "Belas Artes",
        "Reitoria",
        "Creche – Canela",
        "Politécnica",
        "Estacionamento São Lázaro",
      ],
    },
    obs: "Após fechamento de São Lázaro, carro volta para Ondina e retoma rota até último horário.",
  },
  {
    id: "B2",
    name: "Rota B2",
    tripLength: 13,
    departures: [
      "6h00",
      "7h00",
      "8h00",
      "9h00",
      "10h00",
      "11h00",
      "12h00",
      "13:30",
      "14h30",
      "16h00",
      "17h40",
      "18h30",
      "19h50",
      "20h30",
      "21h40",
      "22h30",
    ],
    departureLocation: "Ondina/PAF1",
    arrivalLocation: "Reitoria",
    servedLocations: [
      "Ondina/PAF1",
      "Residência Universitária Garibaldi",
      "Residência I, Vitória",
      "Deli&Cia",
      "Reitoria",
      "Creche",
      "Politécnica",
      "Arquitetura",
      "Geociências",
    ],
    stops: {
      departure: [
        "Ondina/PAF1",
        "Residência Universitária Garibaldi",
        "Arquitetura",
        "São Lázaro",
        "Politécnica",
        "Creche Canela",
        "Reitoria",
      ],
      arrival: [
        "Residência I, Vitória",
        "Deli&Cia",
        "Politécnica",
        "São Lázaro",
        "Arquitetura",
        "Geociências",
        "Ondina/PAF1",
      ],
    },
    obs: "19h50 é o último horário a entrar em São Lázaro",
  },
  {
    id: "B3",
    name: "Rota B3",
    tripLength: 15.5,
    departures: [
      "6h30",
      "7h10",
      "8h40",
      "9h50",
      "11h00",
      "12h10",
      "13h20",
      "14h30",
      "15h40",
      "16h50",
      "18h00",
      "19h10",
      "20h30",
      "21h20",
      "22h20",
    ],
    departureLocation: "Direito",
    arrivalLocation: "Ondina/PAF1",
    servedLocations: [
      "Direito",
      "Música",
      "ISC",
      "Odontologia",
      "Nutrição",
      "Ondina/PAF1",
      "Residência Universitária Garibaldi",
      "Deli&Cia",
      "Reitoria",
      "Creche",
      "Politécnica",
      "Arquitetura",
      "Geociências",
    ],
    stops: {
      departure: [
        "Estac. PAF I — Matemática",
        "Av. Garibaldi Pt. R5",
        "Arquitetura",
        "São Lázaro",
        "Politécnica",
        "Creche — Canela",
        "Reitoria sentido Campo Grande",
        "Retorno — rua Baronesa de Sauípe",
        "Belas Artes",
        "Reitoria",
        "Euclides da Cunha — Deli&cia Acesso à direita",
        "Direito",
      ],
      arrival: [
        "Escola de Música — ISC — Odontologia — Nutrição",
        "Reitoria",
        "Politécnica",
        "Arquitetura",
        "Estacionamento Geociências",
        "Estacionamento PAF I — Matemática",
      ],
    },
    obs: "19h10 é o último horário a entrar em São Lázaro",
  },
  {
    id: "B4",
    name: "Rota B4",
    tripLength: 14,
    departures: [
      "6h20",
      "7h20",
      "8h20",
      "9h30",
      "10h40",
      "11h40",
      "12h40",
      "14h00",
      "15h20",
      "16h30",
      "17h40",
      "20h00",
      "21h20",
      "22h30",
    ],
    departureLocation: "Ondina/PAF1",
    arrivalLocation: "Piedade",
    servedLocations: [
      "Ondina/PAF1",
      "Residência Universitária Garibaldi",
      "Reitoria",
      "Economia",
      "Belas Artes",
      "São Lázaro",
      "Creche",
      "Politécnica",
      "Arquitetura",
      "Geociências",
    ],
    stops: {
      departure: [
        "Estacionamento PAF I Matemática",
        "Av. Garibaldi Pt. R5",
        "Arquitetura",
        "Politécnica",
        "Creche — Canela",
        "Reitoria",
        "Rua Direita da Piedade",
      ],
      arrival: [
        "Piedade",
        "Belas artes",
        "Reitoria",
        "Creche / Canela",
        "Politécnica",
        "São Lázaro",
        "Arquitetura",
        "Estacionamento Geociências",
        "Estacionamento PAF I Matemática",
      ],
    },
    obs: "18:50 é o último horário a entrar em São Lázaro",
  },
  {
    id: "B5",
    name: "Rota B5",
    tripLength: 17,
    departures: [
      "6h20",
      "7h20",
      "8h40",
      "10h00",
      "11h20",
      "12h40",
      "14h00",
      "15h20",
      "16h40",
      "18h00",
      "19h20",
      "20h40",
      "22h20",
    ],
    departureLocation: "Facom",
    arrivalLocation: "Reitoria",
    servedLocations: [
      "Facom",
      "Residência Universitária Garibaldi",
      "Arquitetura",
      "São Lázaro",
      "Politécnica",
      "Creche",
      "Reitoria",
      "Geociências",
      "Residência I, Vitória",
      "Deli&Cia",
      "Ondina/PAF1",
    ],
    stops: {
      departure: [
        "Instituto de Geociências",
        "Facom",
        "Portaria Principal",
        "Centro Esportes",
        "Av. Garibaldi P. R5",
        "Proae",
        "São Lázaro",
        "Politécnica",
        "Creche — Canela",
        "Reitoria",
      ],
      arrival: [
        "Campo Grande",
        "Residência I — P. de Dist. Vitória",
        "Deli&cia — Acesso Direito",
        "Politécnica",
        "São Lázaro",
        "Arquitetura",
        "Estac. PAF I — Matemática",
        "Facom",
        "Instituto de Geociências",
      ],
    },
    obs: "19h20 é o último horário a entrar em São Lázaro",
  },
];
